//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syntage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syntage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Noise
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.15
        ///EADec     0.99
        ///EAStn     0.00
        ///EARel     0.23
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.01
        ///FPass     LowPass
        ///FCutoff   1129.30
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    Off
        ///DlyDry    1.00
        ///DlySec    5.00
        ///DlyFbck   1.00
        ///KClip     On
        ///GOsc      Square
        ///GFrq      21.05
        ///GMtch     True
        ///GGain     1.00
        ///GNum      AP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Butterfly {
            get {
                return ResourceManager.GetString("Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Sine
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.01
        ///EADec     0.01
        ///EAStn     1.00
        ///EARel     0.01
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.01
        ///FPass     LowPass
        ///FCutoff   1129.30
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    Off
        ///DlyDry    1.00
        ///DlySec    5.00
        ///DlyFbck   1.00
        ///KClip     On
        ///GOsc      Sine
        ///GFrq      3.61
        ///GMtch     True
        ///GGain     1.00
        ///GNum      AFine        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Elastic {
            get {
                return ResourceManager.GetString("Elastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Sine
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.01
        ///EADec     0.01
        ///EAStn     1.00
        ///EARel     0.01
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.01
        ///FPass     LowPass
        ///FCutoff   1129.30
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    Off
        ///DlyDry    1.00
        ///DlySec    5.00
        ///DlyFbck   1.00
        ///KClip     On
        ///GOsc      Sine
        ///GFrq      3.61
        ///GMtch     True
        ///GGain     1.00
        ///GNum      AFine        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FineFeedback {
            get {
                return ResourceManager.GetString("FineFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Sine
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.01
        ///EADec     0.01
        ///EAStn     1.00
        ///EARel     0.01
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.01
        ///FPass     None
        ///FCutoff   20000.00
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    Off
        ///DlyDry    1.00
        ///DlySec    5.00
        ///DlyFbck   1.00
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      1000.00
        ///GMtch     False
        ///GGain     1.00
        ///GNum      Non [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.50
        ///AVol      0.00
        ///AOsc      Square
        ///AFine     -0.12
        ///APan      0.40
        ///EAAtk     0.02
        ///EADec     0.01
        ///EAStn     1.00
        ///EARel     0.01
        ///BVol      0.00
        ///BOsc      Square
        ///BFine     0.11
        ///BPan      0.60
        ///EBAtk     0.03
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.01
        ///FPass     LowPass
        ///FCutoff   1755.61
        ///DPwr      Off
        ///DTrshd    0.10
        ///DlyPwr    On
        ///DlyDry    0.90
        ///DlySec    0.39
        ///DlyFbck   0.50
        ///KClip     On
        ///GOsc      Sine
        ///GFrq      0.01
        ///GMtch     False
        ///GGain     0.00
        ///GNum      - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Synt1 {
            get {
                return ResourceManager.GetString("Synt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.50
        ///AVol      0.00
        ///AOsc      Square
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.01
        ///EADec     0.01
        ///EAStn     1.00
        ///EARel     0.21
        ///BVol      0.00
        ///BOsc      Saw
        ///BFine     2.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.21
        ///FPass     LowPass
        ///FCutoff   420.29
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    On
        ///DlyDry    1.00
        ///DlySec    5.00
        ///DlyFbck   0.00
        ///KClip     Off
        ///GOsc      Sine
        ///GFrq      2.64
        ///GMtch     False
        ///GGain     1.00
        ///GNum      CMix        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Synt2 {
            get {
                return ResourceManager.GetString("Synt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.10
        ///AVol      0.00
        ///AOsc      Triangle
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.07
        ///EADec     0.24
        ///EAStn     0.55
        ///EARel     0.01
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.21
        ///FPass     None
        ///FCutoff   20000.00
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    On
        ///DlyDry    0.75
        ///DlySec    0.24
        ///DlyFbck   0.85
        ///KClip     Off
        ///GOsc      Triangle
        ///GFrq      4.65
        ///GMtch     True
        ///GGain     1.00
        ///GNum       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Synt3 {
            get {
                return ResourceManager.GetString("Synt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPwr      On
        ///CMix      0.00
        ///AVol      0.00
        ///AOsc      Sine
        ///AFine     0.00
        ///APan      0.50
        ///EAAtk     0.01
        ///EADec     0.01
        ///EAStn     1.00
        ///EARel     0.01
        ///BVol      0.00
        ///BOsc      Sine
        ///BFine     0.00
        ///BPan      0.50
        ///EBAtk     0.01
        ///EBDec     0.01
        ///EBStn     1.00
        ///EBRel     0.01
        ///FPass     LowPass
        ///FCutoff   1129.30
        ///DPwr      Off
        ///DTrshd    1.00
        ///DlyPwr    Off
        ///DlyDry    1.00
        ///DlySec    5.00
        ///DlyFbck   1.00
        ///KClip     On
        ///GOsc      Square
        ///GFrq      8.18
        ///GMtch     True
        ///GGain     1.00
        ///GNum      AFin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
    }
}
